### ISSUE TITLE
Consider usage of alternative fonts for PL and EO lqdn-gafam-campaign translation

### ISSUE THREAD

**Issue by Informatic** [posterkit/posterkit-sandbox#1]
So far, these fonts seem to be pretty similar to Futura:

https://github.com/ossobuffo/didact-gothic ← this seems to be the most similar do far?
http://www.latofonts.com/lato-free-fonts/
https://github.com/itfoundry/hind ("for Google Fonts" - rather ironic, isn't it; doesn't support esperanto-specific characters, as far as I see)
https://github.com/vernnobile/MuliFont

Implementation-wise - it seems that it'd be easiest to just replace `font-family` on all elements on pl/eo langauges in `layout_rules_override`, but haven't dug into it too much...

**Comment by amotl** [comment]
Thanks for your recommendations, Piotr. We will have a look into that soon!

**Comment by amotl** [comment]
Dear Piotr,

sorry for the delay and thanks for your patience, we are just getting back to this. Let us report while revisiting your suggestions:
- The [Didact Gothic](https://fonts.google.com/specimen/Didact+Gothic) font looks similar, but we found it a little bit thin to make up the body text and there are no Didact Gothic "Black" or "Heavy" variants, unfortunately - right? It would probably be okay for the footer text.
- The [Lato Black](http://www.latofonts.com/lato-free-fonts/) font looks pretty decent, [Muli Black](https://fonts.google.com/specimen/Muli) looks even better, thanks!

With kind regards.

**Comment by amotl** [comment]
After investigating further by trial and error, we found **Muli Black** also seems to lack some characters required for displaying the translations into Polish and Esperanto properly, so we will be going with **Lato Heavy** for the body text and **Lato Regular** for the footer text.

To be more precise, we will use the Lato fonts at **both** the body- and footer-texts for the translation into **Polish**, while we will use it at the **footer text only** for the translation into **Esperanto**, as the corresponding body texts do not contain any characters with diacritics.

Thanks again for your suggestions!

**Comment by amotl** [comment]
Dear @Informatic,

we implemented the changes as described above and introduced the **Lato Heavy** and **Lato Regular** fonts where appropriate by amending `layout_rules_override` (see https://github.com/posterkit/posterkit-sandbox/commit/fcbd4ba), as you suggested.

Can we humbly ask you to review the recently released renderings of the translations into Polish and Esperanto? You can find them in colored variants right here:
- https://ptrace.gafam.info/unofficial/pdf/color/lqdn-gafam-poster-pl-color.pdf
- https://ptrace.gafam.info/unofficial/pdf/color/lqdn-gafam-poster-eo-color.pdf

Please also enjoy the whole gallery of languages and renderings at https://library.gafam.info/.

Thanks again for pointing out this font issue to us and cheers!

**Comment by Informatic** [comment]
Hey! Typography looks great now.

Just a slightly unrelated comment - is "Microsoft" logo supposed to be
green, when all the other company logos are white?

**Comment by amotl** [comment]
Hey Piotr,

> Typography looks great now.

Excellent!

> is [the] "Microsoft" logo supposed to be green, when all the other company logos are white?

Thanks for noticing, we moved this to #2.

**Comment by amotl** [comment]
Let's just have a look at the LQDN logo itself. Currently, we use two variants:
- [logo-lqdn-dark.svg](https://github.com/posterkit/posterkit-sandbox/blob/master/htdocs/examples/lqdn-gafam-campaign/img/logo-lqdn-dark.svg)
- [logo-lqdn-white.svg](https://github.com/posterkit/posterkit-sandbox/blob/master/htdocs/examples/lqdn-gafam-campaign/img/logo-lqdn-white.svg)

We currently believe we will need a third - colored - variant. However, it would be very cool to handle the coloring at runtime in order to keep maintenance low when changing colors or adding more variants, at least for all of the SVG images.

Do you see any way to achieve this?

P.S.: We didn't do research on that topic yet, just asking whether you know anything out of thin air ;].
